language: java

install: true

jdk:
  - openjdk8

before_script:
  - chmod +x gradlew

script:
  - ./gradlew check
  - ./gradlew build --scan -s
  - ./gradlew codeCoverageReport

after_success:
  - bash <(curl -s https://codecov.io/bash)

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache.directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/

deploy:
  provider: releases
  api_key.secure: B/yArHFAtSJ4F5I6u/TM4BQHb4iMWzz7CYep7CYYklWamh2cCKvsG7FBWIV04z4C8tNroLsvJ6eDvjwjTFg1TTBqn8uPvatFEwGaEEXD7JYLlkC/kqDl9UkCGJG3Z65y7OA8zoqFJ8KiuKj/dZOJnBLXvtkn2/TCIR0ubBahjJVgspB3y2g8JoXfl7GFIkPh8ko464DwzMGV3fk90XeZfPiDOOURVQVmVF1zH1IZFQONRsUp+lpeQanQJNNGboDznd05j9UcAPe6/0dH6jISA8xbRHy4Y3GofUfSzbYpC3+AAxvNTEK+v+zUosxp97Fw4vV6OkJiNpp2flKY21hC0wAboBTnw4HgXAfoAJnA6GONpufMVbtQ98/fjZDCknxWo5qpNn1RX7x2Gtmr+gSRv6K+gq1w2dL4h024/w3WnT0a03Y9PPk1EkNzSGDadR3J4jUsHnqYzzZDpQOtYfmP6asLjZuX4TAHvDC7S1VYlWz3Umh3SrzBOqVTzzq9F3a2MfkHd/BgpxaEMBC4287rz8G/5Nv54tOATffJ4+vDMlRXZO1CUd8ckO05b38mE2rCL5E27G8Ag6jomEmjiscGOIhEN1U8zGO3m2SySQtY1PZIzFcV5HRYw1RNXbN5pQgocAzLfazYacbpq/QEbZxAiw4I10Fo2dUwmRIuJ85e8Sw=
  file: $HOME/build/libs/*
  on.repo: GabrielCzar/KAESCrypt
  skip_cleanup: true
  on.tags: true
  on.branch: master